### ISSUE TITLE
Remove token check from SlackBot Router

### ISSUE THREAD

**Issue by franz-josef-kaiser** [localytics/lambda-slack-router#26]
Currently the [`buildRouter()`](https://github.com/localytics/lambda-slack-router/blob/987a4a9f0a3845bf95ee7c7eedd0f51424153677/index.js#L154-L156) function checks the token from inside the config against the token from the payload:

```js
if (!body.token || body.token !== token) {
    return context.fail('Invalid Slack token');
}
```

This removes the possibility to use the bot in multiple Slack teams. Currently I work around it like this in my main functions `handler.js` file:

```js
var router = function() {
	return function( event, context ) {
		var body    = qs.parse( event.body );
		var command = this.findCommand( body.text );

		event.args = command.args;
		return this.callCommand( command.commandName, event, context.done );
	}.bind( slackBot );
};
module.exports.handler = router();
```

There should be a change to how the router works to enable a multi-team usage for bots/commands.

**Comment by kddeisz** [comment]
@franz-josef-kaiser If you update to 1.3.1, you can now create `new Slackbot()` without a token, and when it's not in the config it will no longer check

**Comment by franz-josef-kaiser** [comment]
@kddeisz Thanks a lot!

**Comment by franz-josef-kaiser** [comment]
You might want to updated that in the [npmjs docs](https://www.npmjs.com/package/lambda-slack-router) and the `README` as well.
