### ISSUE TITLE
POST with response_url not working

### ISSUE THREAD

**Issue by stormlrd** [localytics/lambda-slack-router#30]
Hi,

I'm breaking all the rules and was hoping you might be able to help me.

Scenario:
Bot A = Hubot
Bot B = lambda-slack-router bot

AWS account has an api gateway and a lambda function setup correctly.
Everything works with a slash command just fine from slack directly to API Gateway and Bot B. Thanks for that btw. it is awesome!

however, when I want to use Bot A to do a POST command against the AWS API Gateway and I use a customised payload; specifically a custom response_url field, which is setup as an incoming webhook slack URL, there is no response in the slack channel from Bot B.

API Gateway is 200 response to Bot A however. 

Lambda seems to be working just fine. No Slack Token errors are in there cloud trail logs. I do get a token error if I try to use CURL to do the POST tho.

I think the issue is the way in which the lambda-slack-router is using the response_url ?? probably wrong about that lol :) It is a total guess.

Can you provide some insight into how the router uses or does not use the response_url from a POST payload?

the slash command says:
Your URL should respond with the text to reply to the user unless no response is necessary. If responding, the response must be returned within 3000ms of the request. Any non-200 response will result in an error to the user. You may also send delayed or multiple responses by invoking the response_url.

When using CURL I am not sure if I should be using payload=, body=, message=, text= either.

e.g: curl -X POST --data-urlencode 'body={"Token":"my slash commands token","team_id":"myteamid","team_domain":"example","channel_id":"mychannelid","channel_name":"test","user_id":"myuserid","command":"/slackbot","text":"sayhi","response_url":"url to my incoming webhook"}' https://urltomyapithatisthesameasmyslashcommandinslack

Any help / ideas would be great!

Thanks.

**Comment by kddeisz** [comment]
Hi Paul - just wanted to let you know that I saw this come in. I don't have an immediate response to you, but I'll be able to dig into this tomorrow, so I'll let you know then.

**Comment by kddeisz** [comment]
So the router isn't actually doing anything with the `response_url` field. Provided you're using calling the callback, it's just fulfilling the initial request, it's not itself sending out any messages.

I wonder if it's just swallowing a bad request. Could you check CloudWatch and see what's being written to the logs? You could also use the serverless logs command to get them.

Also, shot in the dark but my requests typically look more like
```
curl -X POST -H 'Content-type: application/json' --data '{"text":"sayhi", "token": "<token>"}' https://<url>
```

when I'm testing. Difference being specifying the content type and using --data instead of --data-urlencode, also no body=. Let me know if any of these things work.

**Comment by stormlrd** [comment]
Thanks for that.  

If I use your CURL command above with the http://url being the slack incoming webhook - it works fine.  If I use it against the API Gateway created by the serverless framework for the slackbot. I get invalid token.

I thought the API Gateway was configured for a Body Mapping to translate urlencoded data and hand it off to the lambda function as json; and that the slack slash command sends in urlencoded to the API endpoint?

If the router is not doing anything with the response_url I guess thats my fundamental issue anyway as the slack router is expecting a proper incoming request from Slack itself and they hold open their initial call to the API Gateway expecting data to be returned.

In my case I'm using hubot to send a POST to the API Endpoint and its finished once it sends. I dont care about data coming back.  Maybe I should :(  I was hoping to pass off to slackbot and have it use the response_url to then initiate an outbound request to a slack incoming webhook instead.

Would that be hard to code into the router???

**Comment by kddeisz** [comment]
It's not that difficult to write into your own slackbot, and I'd rather keep the router pretty simple. I've actually had to do something similar to this before, and I can share my code structure here:

```javascript
slackbot.addCommand('test', 'Test command', (event, callback) => {
  return fetch(event.body.response_url, { method: 'POST', body: JSON.stringify({ hello: 'world' }) }).then(() => {
    callback(null, slackbot.inChannelResponse({}));
  });
});
```

This uses [node-fetch](https://www.npmjs.com/package/node-fetch) package to hit the endpoint with the hello world payload and then responds to the slack payload after the fetch has been completed. Note that you'll need to be on the latest version of the router for this too work.
